
try{
    console.log(varError)
}catch(err){
    console.log('Erro de execução')
}
